server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

dubbo:
  application:
    name: personal-blog
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: multicast://224.5.6.7:10086
    parameters:
      unicast: false
    id: myregistry

